### ISSUE TITLE
Text style and icon in accordion item

### ISSUE THREAD

**Issue by fcoveram** [creativecommons/creativecommons-certificate#11]
## Description
**Page: Home**
Two visual improvements:
1. The answer displayed in the accordion item looks too similar to the question. That's because of the styles of both texts. My suggestion is to apply a bold style for question text.
2. The arrow aligns on the right should be `20px` size (`1.25rem`).
3. The same icon does not rotate when opening the question to see the answer. It should rotate in 180º to indicate the box expanded.

## Screenshot
<img width="857" alt="Screen Shot 2020-11-26 at 15 34 08" src="https://user-images.githubusercontent.com/895819/100383638-d662df00-2ffc-11eb-84da-6bc748bfad1a.png">

**Comment by zackkrida** [comment]
<img width="635" alt="2021-01-22-119" src="https://user-images.githubusercontent.com/6351754/105561642-6f3f6f00-5cbb-11eb-8754-572836222112.png">
<img width="629" alt="2021-01-22-118" src="https://user-images.githubusercontent.com/6351754/105561643-70709c00-5cbb-11eb-90d6-b40353b1dc5a.png">

note: the green outline is visible when the user focuses with their keyboard (tabbing trough the accordions) but not when they click the accordions with the mouse cursor.
