### ISSUE TITLE
Padding between dates within course card

### ISSUE THREAD

**Issue by fcoveram** [creativecommons/creativecommons-certificate#13]
## Description
In the course date card, the space between dates is not `4px`. It should have space in between.

## Screenshots
<img width="190" alt="Screen Shot 2020-11-26 at 15 39 08" src="https://user-images.githubusercontent.com/895819/100384092-124a7400-2ffe-11eb-9f46-581f2a300099.png">

**Comment by zackkrida** [comment]
Could you explain this more? Is it horizontal/vertical padding missing, between what exactly?

**Comment by panchovm** [comment]
I meant the vertical space, between January 01 and January 22 labels. That space seems too tight compared to the mockups.
