### ISSUE TITLE
Testing Notes

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/creativecommons-certificate#7]
The theme is ready to test. Here are some notes about, well, everything!

https://tempcert.creativecommons.org/
(same login credentials for everyone as live certificate site)

## Remaining TODOs

- [x] [1hr] Fix new header styling issues (ticket here: https://github.com/creativecommons/vocabulary/issues/805)
- [ ] Push Alumni section PR
  - [x] [30min] Finish responsive styles for Alumni pages
  - [x] [1hr] Finish custom BB press styles
- [x] [45min] Add black attribution bar to course featured images + scholarship recipients
- [x] [30min] Fix course responsive styles (I think I lost a commit)
- [x] [?] Debug Candela issue on staging server (PHP critical error when activating *Candela Utilities* plugin), seems to be related to symlinks/paths 

---

### Pressbooks Issues

- Pressbooks **does not** support Gutenberg. This means we are not using `wp-plugin-vocabulary-blocks` as originally planned.
  - Post explaining the lack of support: https://pressbooks.org/blog/2018/11/06/pressbooks-and-gutenberg/
  - More discussions of gutenberg support: https://github.com/pressbooks/pressbooks/issues?q=gutenberg
  - [Pressbooks mPDF](https://github.com/BCcampus/pressbooks-mpdf) is deprecated, so we cannot currently download books as PDFs. There are some options but they require addtional dependencies. One thing we could try doing is exporting `.epub` books inthe future, and then converting the epub files to PDFs, but we'll have to test the stying.
    - Info on the [other options](https://docs.pressbooks.org/installation/#part-3-pressbooks-dependencies), none of them are great.

#### Other Plugin Issues

- LTI functionality has been preserved. I'm not sure if it actually works or is being used!
- The **Candela Attributions** and Candela Utilities plugins are kept, but I can't tell if they are being used or not. These plugins are deprecated and difficult to install with git+composer. **If we can remove or ignore them, we should.**
  - I tried to test several book pages but couldn't actually find any with attributions.
- **Breadcrumb NavXT** is removed in favor of Yoast SEOs breadcrumbs. The breadcrumbs on this site are simple enough where we don't need a more complex implementation, and 

### Content questions 

- There was no archive page for **courses** mocked up. How do we want to handle that?
- The Registration link(s) is a global setting on the options page but can also be overwritten per-course if necessary. Does this sound like good behavior?

### General

- Code was formatted with `phpcbf --standard=WordPress . --ignore=vendor --extensions=php 0`. If there's a better approach please let me know; I've always struggled to find good PHP linters and formatters where I was happy with the output. 
- Because this theme was unable to use Gutenberg blocks and, while relatively simple, has a lot of custom templates, I decided to use **Advanced Custom Fields Pro** to register metaboxes on page templates, as opposed to our usual combination of Queulat and widgets. I think this provides a really great experience for content editors, and reduces the amount of boilerplate code we have to write to register metaboxes with rich, complicated functionality. If there's a critical reason we do not want to go this direction, we _can_ switch back to Queulat with some work. The templates wouldn't need to change much but we'd need to write all the Queulat code to register metaboxes.

**Comment by zackkrida** [comment]
@hugosolar Here's a copy of my local DB: 

https://drive.google.com/file/d/1YAjVoLxGu9jnkbzwL_SpcwkwVEDPGIDt/view?usp=sharing

My local domain is: https://certs-backup.test/ if you want to do a find/replace. 

I will be pushing my DB to https://tempcert.creativecommons.org/ today if you want to wait to test until then :)

**Comment by panchovm** [comment]
Wonderful. I will start now reviewing the site. Regarding your content questions:
1. There are three types of courses, and my understanding is that the only archive is past dates. Therefore, the only archive should be the calendar page.
2. I strongly agree with you. That will depend on the software feasibility we are using for recording applications.

In both cases, let's double-check this Monday during the presentation meeting with Jennryn.

**Comment by zackkrida** [comment]
Closing as this PR contained notes, not actual actionable issues.
