### ISSUE TITLE
Incorrect text style in descriptive paragraph

### ISSUE THREAD

**Issue by fcoveram** [creativecommons/creativecommons-certificate#9]
## Description
**Page: Home**
The paragraph below the main title uses an incorrect style. It should have the `body-bigger` style.

## Screenshot
<img width="558" alt="Screen Shot 2020-11-26 at 15 22 39" src="https://user-images.githubusercontent.com/895819/100382959-3eb0c100-2ffb-11eb-9a70-51736994379f.png">

**Comment by JigarJoshi04** [comment]
I can work on this.
Please assign this to me or
please update the status of the issue
